name: ta_smt4
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  bloc: ^8.1.0
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  file_picker: ^5.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_launcher_icons: ^0.10.0
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_randomcolor: ^1.0.14
  flutter_secure_storage: ^8.0.0
  fresh_dio: ^0.3.2
  get_it: ^7.2.0
  image_picker: ^0.8.6
  injectable: ^2.1.0
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  logger: ^1.1.0
  path: ^1.8.2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sprintf: ^7.0.0
  time_machine: ^0.9.17
  url_launcher: ^6.1.6
  permission_handler: ^10.2.0
  cupertino_icons: ^1.0.2
  easy_sidemenu: ^0.4.1+1

dev_dependencies:
  build_runner: ^2.2.1
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_native_splash: any
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3


flutter:
  uses-material-design: true
  
  generate: false

  # assets:
    # Add assets from the images directory to the application.
